# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openappwrapper.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14openappwrapper.proto\x12\x0eopenappwrapper\"=\n\x0e\x43ommandRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x0c\n\x04mode\x18\x02 \x01(\t\x12\x0c\n\x04user\x18\x03 \x01(\t\"\x1d\n\nDebugReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1a\n\x02Id\x12\x14\n\x0cmachine_name\x18\x01 \x01(\t2\x9a\x01\n\x06Opener\x12\x44\n\x04Open\x12\x1e.openappwrapper.CommandRequest\x1a\x1a.openappwrapper.DebugReply\"\x00\x12J\n\x10ListenForContent\x12\x12.openappwrapper.Id\x1a\x1e.openappwrapper.CommandRequest\"\x00\x30\x01\x42\x06\xa2\x02\x03HLWb\x06proto3')



_COMMANDREQUEST = DESCRIPTOR.message_types_by_name['CommandRequest']
_DEBUGREPLY = DESCRIPTOR.message_types_by_name['DebugReply']
_ID = DESCRIPTOR.message_types_by_name['Id']
CommandRequest = _reflection.GeneratedProtocolMessageType('CommandRequest', (_message.Message,), {
  'DESCRIPTOR' : _COMMANDREQUEST,
  '__module__' : 'openappwrapper_pb2'
  # @@protoc_insertion_point(class_scope:openappwrapper.CommandRequest)
  })
_sym_db.RegisterMessage(CommandRequest)

DebugReply = _reflection.GeneratedProtocolMessageType('DebugReply', (_message.Message,), {
  'DESCRIPTOR' : _DEBUGREPLY,
  '__module__' : 'openappwrapper_pb2'
  # @@protoc_insertion_point(class_scope:openappwrapper.DebugReply)
  })
_sym_db.RegisterMessage(DebugReply)

Id = _reflection.GeneratedProtocolMessageType('Id', (_message.Message,), {
  'DESCRIPTOR' : _ID,
  '__module__' : 'openappwrapper_pb2'
  # @@protoc_insertion_point(class_scope:openappwrapper.Id)
  })
_sym_db.RegisterMessage(Id)

_OPENER = DESCRIPTOR.services_by_name['Opener']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\242\002\003HLW'
  _COMMANDREQUEST._serialized_start=40
  _COMMANDREQUEST._serialized_end=101
  _DEBUGREPLY._serialized_start=103
  _DEBUGREPLY._serialized_end=132
  _ID._serialized_start=134
  _ID._serialized_end=160
  _OPENER._serialized_start=163
  _OPENER._serialized_end=317
# @@protoc_insertion_point(module_scope)
