# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import openappwrapper_pb2 as openappwrapper__pb2


class OpenerStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Open = channel.unary_unary(
                '/openappwrapper.Opener/Open',
                request_serializer=openappwrapper__pb2.CommandRequest.SerializeToString,
                response_deserializer=openappwrapper__pb2.DebugReply.FromString,
                )
        self.ListenForContent = channel.unary_stream(
                '/openappwrapper.Opener/ListenForContent',
                request_serializer=openappwrapper__pb2.Id.SerializeToString,
                response_deserializer=openappwrapper__pb2.CommandRequest.FromString,
                )


class OpenerServicer(object):
    """The greeting service definition.
    """

    def Open(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListenForContent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OpenerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Open': grpc.unary_unary_rpc_method_handler(
                    servicer.Open,
                    request_deserializer=openappwrapper__pb2.CommandRequest.FromString,
                    response_serializer=openappwrapper__pb2.DebugReply.SerializeToString,
            ),
            'ListenForContent': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenForContent,
                    request_deserializer=openappwrapper__pb2.Id.FromString,
                    response_serializer=openappwrapper__pb2.CommandRequest.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'openappwrapper.Opener', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Opener(object):
    """The greeting service definition.
    """

    @staticmethod
    def Open(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/openappwrapper.Opener/Open',
            openappwrapper__pb2.CommandRequest.SerializeToString,
            openappwrapper__pb2.DebugReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListenForContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/openappwrapper.Opener/ListenForContent',
            openappwrapper__pb2.Id.SerializeToString,
            openappwrapper__pb2.CommandRequest.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
